language: node_js
sudo: required

matrix:
  include:
    # LINUX
    - os: linux
      dist: trusty
      node_js: 6
      env:
          - GULP_PLATFORM=linux
    # MAC
    - os: osx
      osx_image: xcode8  # currently xcode8.1+ doesn't support electron-builder macOS code-signing (https://github.com/electron-userland/electron-builder/issues/820#issuecomment-267777060)
      node_js: 6
      env:
          - GULP_PLATFORM=mac

  allow_failures:
  - os: osx
  #fast_finish: true

cache:
  directories:
  - node_modules

services:
- docker

before_install: 
- npm install -g electron
- "./setup.sh"
- npm install
- "./buildhtml.sh"
install:
  - npm install -g codecov
script: 
- if [[ $TRAVIS_OS_NAME == "linux" ]]; npm test -- --coverage; fi;
- if [[ $TRAVIS_OS_NAME == "linux" ]]; codecov; fi;
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then ./install.sh; fi;
- if [[ $TRAVIS_OS_NAME == "osx" ]]; then npm run distMac; fi;

after_success:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; bash <(curl -s https://codecov.io/bash); fi;  

deploy:
  provider: releases
  api_key:
    secure: SAEIy7xvJFVk+TCAb46c1KfLtPOkUblYXM43kcl8cWoqxSDT4XlWc7DTx5ZX9M3GD2+iQu7W5Ed4jMetRA6VSyR0UnTBe+/bQ0HpvR6zMPstb2gWZ7AFR30WYIbGDe/GqarmxDbJJj4umYaMiOMOzuvj4XzthFZud5TzEOcHRy8++KCJc9WrV1eUvXm9vokrKyOG9qcmwdM3dxHzKDII9QFPKrVDpw5OqBIivsuGM6q1PrNTFn5RqGfjwRbST3zlowVS+CF24d7fi/a4RJpsc74NhnMbz9LJSH3LXfU1nxoGoXVqrT4z46UvVd0Ha9Pm9/tO+MI+FJ2BqLG7I4KtNMIiTiLZdz19Me7aWyKta23IC5akWNt64AX4912yVeJgSNjVMisTxmm9wEt6VF0rsPqb8vHleup4yXt3J5D1A8NL/NMo8OXmiAhAwIC+s+jaaNgmvSVAiJOFcYrQFGWHH1o0J4TsfiguCGnR39hoOZAW4syLlzPm7XP5sp7++E4DEkBA2YpiM4AldAAb0FBdYpeWQCqLBIfEtzlFdUOxJKyH+rgkABn7uw8P7r+oOlmMlLpAh9aR4rp8ZPJzH3Ly0qEtbLQU3BTazBqL1IJhFKw67neCbvmPfQxnQdsvABaujDcea2EASTaLiemKE0ApLbM0u8DjmTQ9ZBbcntkAiVw=
  file_glob: true
  file: 
   - "./dist/skypetdesktop_*.deb"
   - "./dist/mac/skypetdesktop-*.dmg" 
   - "./dist/skypetdesktop Setup*.exe"
   - "./dist/skypetdesktop*.zip"
  skip_cleanup: true
  on:
    repo: SkyPet/SkyPetDesktop
    tags: true
